### ISSUE TITLE
User can view recipes on feed

### ISSUE THREAD

**Issue by Claodicus** [IOS-Group-38-Milestone/Recipe-Playlist#5]
Need to define: data model for recipes

For the feed view, show picture, title, author, tags, time needed to cook

**Comment by Claodicus** [comment]
Yulduz, I assigned this to you but you don't have do it all yourself or do it all this sprint necessarily. Just see what you can do, rely on the parstagram code as a template. Use slack if you have any questions

**Comment by YulduzM1** [comment]
Completed
